- name: Install Java JDK (for Jenkins)
  apt:
    name:
      - fontconfig
      - openjdk-17-jre
    state: present
    update_cache: yes

- name: Create keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /etc/apt/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins apt repository (LTS version)
  copy:
    dest: /etc/apt/sources.list.d/jenkins.list
    content: |
      deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start and enable Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: true

- name: Create /opt/secrets directory for incoming secrets
  file:
    path: /opt/secrets
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Install kubectl on Jenkins
  get_url:
    url: https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Set system-wide KUBECONFIG for all users (including Jenkins)
  lineinfile:
    path: /etc/environment
    line: 'KUBECONFIG=/opt/secrets/kubeconfig'
    create: yes

- name: Add KUBECONFIG to Jenkins systemd environment
  lineinfile:
    path: /etc/default/jenkins
    line: 'KUBECONFIG=/opt/secrets/kubeconfig'
    create: yes

- name: Restart Jenkins to apply environment changes
  systemd:
    name: jenkins
    state: restarted


