---
- name: Gerekli paketleri yükle
  apt:
    name:
      - openjdk-17-jre
      - git
      - curl
    state: present
    update_cache: yes

- name: Jenkins kullanıcı ve grubunu oluştur
  user:
    name: "{{ jenkins_user }}"
    create_home: yes
    shell: /bin/bash

- name: Jenkins ana dizinini oluştur
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'

- name: Plugins dizinini oluştur
  file:
    path: "{{ plugins_dir }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'

- name: jcasc.yaml dosyasını kopyala
  copy:
    src: "{{ playbook_dir }}/roles/jenkins/files/jcasc.yaml"
    dest: "{{ jcasc_path }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0644'
    force: yes


- name: Plugin listesini kopyala
  copy:
    src: jenkins_plugins.txt
    dest: "{{ jenkins_home }}/jenkins_plugins.txt"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0644'

- name: Jenkins WAR dosyasını indir
  get_url:
    url: "{{ jenkins_url }}"
    dest: "{{ jenkins_home }}/jenkins.war"
    mode: '0755'

- name: Plugin manager jar dosyasını indir
  get_url:
    url: "{{ plugin_manager_url }}"
    dest: "{{ jenkins_home }}/jenkins-plugin-manager.jar"
    mode: '0755'

- name: Gerekli Jenkins pluginlerini indir (plugin dosyasından)
  command: >
    java -jar {{ jenkins_home }}/jenkins-plugin-manager.jar
    --war {{ jenkins_home }}/jenkins.war
    --plugin-download-directory {{ plugins_dir }}
    --plugin-file {{ jenkins_home }}/jenkins_plugins.txt
  args:
    creates: "{{ plugins_dir }}/configuration-as-code.jpi"

- name: Systemd servisi için jenkins.service dosyasını oluştur
  copy:
    dest: /etc/systemd/system/jenkins.service
    content: |
      [Unit]
      Description=Jenkins WAR Service
      After=network.target

      [Service]
      Type=simple
      User={{ jenkins_user }}
      Environment="JENKINS_HOME={{ jenkins_home }}"
      Environment="CASC_JENKINS_CONFIG={{ jcasc_path }}"
      ExecStart=/usr/bin/java -jar {{ jenkins_home }}/jenkins.war --httpPort=8080 --webroot={{ jenkins_home }}/war
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify:
    - daemon-reload

- name: Jenkins servisini başlat ve etkinleştir
  systemd:
    name: jenkins
    enabled: true
    state: started

- name: /opt/secrets dizinini oluştur
  file:
    path: /opt/secrets
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: '0755'

- name: kubectl kurulum dosyasını indir
  get_url:
    url: https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Docker için gerekli bağımlılıkları yükle
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Docker GPG anahtarını ekle
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker repository'sini ekle
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Docker Engine'i kur
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Jenkins kullanıcısını docker grubuna ekle
  user:
    name: "{{ jenkins_user }}"
    groups: docker
    append: yes

- name: Docker servisini başlat ve etkinleştir
  systemd:
    name: docker
    enabled: true
    state: started


- name: Trivy v0.63.0 tar.gz dosyasını indir
  get_url:
    url: https://github.com/aquasecurity/trivy/releases/download/v0.63.0/trivy_0.63.0_Linux-64bit.tar.gz
    dest: /tmp/trivy.tar.gz
    mode: '0755'

- name: Trivy arşivini çıkar
  unarchive:
    src: /tmp/trivy.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Trivy binary'yi /usr/local/bin/trivy olarak taşı (dosya içindeyse)
  command: mv /usr/local/bin/trivy /usr/local/bin/trivy
  args:
    creates: /usr/local/bin/trivy
  ignore_errors: yes  # varsa taşı, yoksa geç

- name: Trivy çalışabilirliğini doğrula
  command: trivy --version
  register: trivy_version_output
  changed_when: false

- name: Trivy versiyon çıktısını göster
  debug:
    msg: "{{ trivy_version_output.stdout }}"

