- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Add Nexus user
  user:
    name: nexus
    shell: /bin/bash
    create_home: yes

- name: Download Nexus (Linux version)
  get_url:
    url: https://download.sonatype.com/nexus/3/nexus-3.80.0-06-linux-x86_64.tar.gz
    dest: /opt/nexus.tar.gz

- name: Extract Nexus
  unarchive:
    src: /opt/nexus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Set directory ownership
  file:
    path: /opt/nexus-3.80.0-06
    owner: nexus
    group: nexus
    recurse: yes

- name: Create working directory
  file:
    path: /opt/sonatype-work/nexus3
    state: directory
    owner: nexus
    group: nexus
    mode: '0755'
    recurse: yes

- name: Configure nexus.rc
  copy:
    dest: /opt/nexus-3.80.0-06/bin/nexus.rc
    content: |
      RUN_AS_USER=nexus
      HOME=/opt/nexus-3.80.0-06
    owner: nexus
    group: nexus
    mode: '0644'

- name: Disable random admin password generation
  lineinfile:
    path: /opt/sonatype-work/nexus3/etc/nexus.properties
    line: 'nexus.security.randompassword=false'
    create: yes
    owner: nexus
    group: nexus
    mode: '0644'

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/nexus.service
    content: |
      [Unit]
      Description=Nexus Repository Manager
      After=network.target

      [Service]
      Type=forking
      LimitNOFILE=65536
      ExecStart=/opt/nexus-3.80.0-06/bin/nexus start
      ExecStop=/opt/nexus-3.80.0-06/bin/nexus stop
      User=nexus
      Restart=on-abort

      [Install]
      WantedBy=multi-user.target

- name: Reload and start Nexus service
  block:
    - command: systemctl daemon-reload
    - systemd:
        name: nexus
        enabled: yes
        state: started


- name: Write Nexus IP to temp file
  copy:
    content: "{{ ansible_host }}"
    dest: /tmp/nexus_ip

- name: Fetch Nexus IP file
  fetch:
    src: /tmp/nexus_ip
    dest: /tmp/secrets/
    flat: yes

- name: Copy Nexus IP file to Jenkins
  copy:
    src: /tmp/secrets/nexus_ip
    dest: /opt/secrets/nexus_ip
  delegate_to: "{{ groups['jenkins'][0] }}"

- name: Set owner and permissions for Nexus IP file on Jenkins
  file:
    path: /opt/secrets/nexus_ip
    owner: jenkins
    group: jenkins
    mode: '0600'
  delegate_to: "{{ groups['jenkins'][0] }}"


- name: /opt/secrets dizinini oluştur Jenkins'te
  file:
    path: /opt/secrets
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0700'
  delegate_to: "{{ groups['jenkins'][0] }}"

- name: Nexus şifresini Jenkins'e kopyala
  copy:
    src: "../../../../jenkins/nexus_password"
    dest: /opt/secrets/nexus_password
    owner: jenkins
    group: jenkins
    mode: '0600'
  delegate_to: "{{ groups['jenkins'][0] }}"
