# jenkins-kubeconfig.yml  (Jinja2 şablonu)
apiVersion: v1
kind: Config
clusters:
- name: k8s
  cluster:
    certificate-authority-data: {{ cacert }}
    server: {{ api_server }}
contexts:
- name: jenkins@k8s
  context:
    cluster: k8s
    user: jenkins
current-context: jenkins@k8s
users:
- name: jenkins
  user:
    token: {{ token }}
