apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181           # aynı isimli Service varsa bu yeterli

            # ↓ Downward API ile pod adı / namespace al
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            # Broker’ların dışarı ve cluster-içi erişim için tek listener
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092

            # Güvenlik haritası tek listener için yeterli
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT

            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          command: [ "sh", "-c" ]
          args:
            - |
              export KAFKA_BROKER_ID=$(echo ${HOSTNAME##*-})
              export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${HOSTNAME}.kafka-headless.${POD_NAMESPACE}.svc.cluster.local:9092
              /etc/confluent/docker/run


  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi

