apiVersion: v1
kind: Service
metadata:
  name: account-order-management
spec:
  selector:
    app: account-order-management
  ports:
  - name: http
    protocol: TCP
    port: 5831
    targetPort: 5831
    nodePort: 31831
  type: NodePort
