apiVersion: v1
kind: Service
metadata:
  name: charging-gateway-function
spec:
  selector:
    app: charging-gateway-function
  ports:
  - name: http
    protocol: TCP
    port: 5833
    targetPort: 5833
  type: ClusterIP
