apiVersion: v1
kind: Service
metadata:
  name: hazelcast-node1
spec:
  selector:
    app: hazelcast-node1
  ports:
  - name: hazelcast-port
    protocol: TCP
    port: 5701
    targetPort: 5701
  type: ClusterIP
