apiVersion: v1
kind: Service
metadata:
  name: ignite-node-1
spec:
  selector:
    app: ignite-node-1
  ports:
  - name: thin-client
    protocol: TCP
    port: 10800
    targetPort: 10800
  - name: jdbc
    protocol: TCP
    port: 10801
    targetPort: 10801
  - name: odbc
    protocol: TCP
    port: 10802
    targetPort: 10802
  - name: rest
    protocol: TCP
    port: 10803
    targetPort: 10803
  type: NodePort
