apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  clusterIP: None                      # Headless service
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
    - name: internal
      port: 29092
