apiVersion: v1
kind: Service
metadata:
  name: management-center
spec:
  selector:
    app: management-center
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30880
  type: NodePort
