apiVersion: v1
kind: Service
metadata:
  name: online-charging-system
spec:
  selector:
    app: online-charging-system
  ports:
  - name: http
    protocol: TCP
    port: 8071
    targetPort: 8071
  type: ClusterIP
