- name: Initialize Kubernetes master
  command: kubeadm init --pod-network-cidr=10.244.0.0/16

- name: Wait for API server to be ready
  shell: |
    until curl --silent --insecure https://127.0.0.1:6443/healthz; do sleep 5; done
  retries: 20
  delay: 5
  register: apiserver_health
  until: apiserver_health.rc == 0

- name: Create .kube directory for ubuntu user
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy kubeconfig to ubuntu user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: '0644'


- name: Deploy Calico CNI
  command: kubectl apply --validate=false -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.1/manifests/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Wait for Calico pods to be ready
  shell: |
    kubectl get pods -n kube-system --no-headers | awk '{print $1}' | \
    xargs -I{} kubectl wait pod/{} -n kube-system --for=condition=Ready --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: join_cmd

- name: Save join command to file
  copy:
    content: "{{ join_cmd.stdout }}"
    dest: /tmp/kubeadm_join_cmd.sh
    mode: '0755'

- name: Fetch join command from master to control machine
  fetch:
    src: /tmp/kubeadm_join_cmd.sh
    dest: fetched_join_cmds/
    flat: yes
  run_once: true

- name: Copy kubeconfig as Jenkins-use secret
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /tmp/kubernetes_master_secret
    remote_src: yes

- name: Fetch kubeconfig from master
  fetch:
    src: /tmp/kubernetes_master_secret
    dest: /tmp/secrets/
    flat: yes
  run_once: true

- name: Copy kubeconfig to Jenkins
  copy:
    src: /tmp/secrets/kubernetes_master_secret
    dest: /opt/secrets/kubeconfig
  delegate_to: "{{ groups['jenkins'][0] }}"
  run_once: true

- name: Set ownership and permissions for Kubernetes master secret on Jenkins
  file:
    path: /opt/secrets/kubeconfig
    owner: jenkins
    group: jenkins
    mode: '0600'
  delegate_to: "{{ groups['jenkins'][0] }}"
  run_once: true

